name: Build FFmpeg 16KB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: sudo apt-get update && sudo apt-get install -y nasm yasm pkg-config

      - name: Download Modern NDK and Compile Engine
        run: |
          wget -q https://dl.google.com/android/repository/android-ndk-r27b-linux.zip
          unzip -q android-ndk-r27b-linux.zip
          export ANDROID_NDK_HOME=$(pwd)/android-ndk-r27b
          ./ffmpeg-android-maker.sh
          
      - name: Save and Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: ffmpeg-16kb-binaries
          path: output/
